SQL E-COMMERCE ANALYSIS

Executive Summary

This project analyses an e-commerce sales dataset using SQL to answer key business questions related to revenue, customer behaviour, product performance and operational efficiency.

The objective is to demonstrate SQL skills by solving real-world business problems using filtering, aggregation, grouping and advanced analytical queries. Each query is followed by business insights and recommendations based on the results.

Tools Used:
- SQL (SQLite)
- Python
- Pandas
- Google Colab

In [1]:
import sqlite3
import pandas as pd

In [2]:
from google.colab import files

uploaded = files.upload()

Saving ecommerce_orders_dataset.csv to ecommerce_orders_dataset.csv

In [3]:
df = pd.read_csv("ecommerce_orders_dataset.csv")

df.head()

,Order_ID,Customer_ID,Order_Date,Year,Month,Day,Day_Of_Week,Quarter,Customer_Age,Customer_Gender,...,Delivery_Days,Order_Status,Returned,Review_Rating,Customer_Lifetime_Value,Profit_Margin_Percent,Profit_Amount,Season,Holiday_Season,High_Value_Order
0,615717,CUST007322,2023-01-01,2023,1,1,Sunday,1,32,Male,...,2,Delivered,No,4.4,2144.92,23.10,15.75,Winter,No,No
1,626919,CUST004717,2023-01-01,2023,1,1,Sunday,1,50,Male,...,9,Delivered,No,4.1,817.17,8.57,3.32,Winter,No,No
2,615781,CUST004415,2023-01-01,2023,1,1,Sunday,1,61,Male,...,2,Delivered,No,5.0,541.16,29.72,45.67,Winter,No,No
3,621747,CUST004114,2023-01-01,2023,1,1,Sunday,1,34,Male,...,6,Returned,Yes,3.4,700.49,25.22,75.25,Winter,No,No
4,625881,CUST000145,2023-01-01,2023,1,1,Sunday,1,37,Male,...,8,Delivered,No,3.6,2133.77,24.64,26.06,Winter,No,No

In [4]:
conn = sqlite3.connect(":memory:")

In [5]:
df.to_sql("orders", conn, index=False, if_exists="replace")

30000

In [6]:
query = """
SELECT COUNT(*) AS Total_Orders
FROM orders;
"""

pd.read_sql(query, conn)

   Total_Orders
0         30000

Insight-

This query calculates the total number of orders processed by the business. It provides a baseline measure of sales activity and overall business scale.

Idea-

Tracking order volume over time to identify seasonal trends and evaluate the effectiveness of marketing campaigns and promotional activities.

In [7]:
query = """
SELECT ROUND(SUM(Order_Amount),2) AS Total_Revenue
FROM orders;
"""

pd.read_sql(query, conn)

   Total_Revenue
0    11370043.99

Insight-

This query calculates the total revenue generated from all completed orders. It provides an overview of the company's sales performance.

Idea-

Monitoring total revenue regularly and compare it across different months or years to identify growth trends and evaluate business performance.

In [8]:
query = """
SELECT ROUND(AVG(Order_Amount),2) AS Average_Order_Value
FROM orders;
"""

pd.read_sql(query, conn)

   Average_Order_Value
0                379.0

Insight-

The average order value measures how much customers spend per transaction. It is a key indicator of customer purchasing behaviour.

Recommendation-

Increase the average order value through product bundles, cross-selling and personalised recommendations.

In [9]:
query = """
SELECT COUNT(DISTINCT Customer_ID) AS Total_Customers
FROM orders;
"""

pd.read_sql(query, conn)

   Total_Customers
0             8683

Insight-

This query identifies the total number of unique customers who have placed orders.

 Recommendation-

Compare customer growth over time to understand acquisition trends and customer retention.

In [10]:
query = """
SELECT
    Country,
    ROUND(SUM(Order_Amount),2) AS Revenue
FROM orders
GROUP BY Country
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

          Country     Revenue
0    Saudi Arabia  1196810.50
1   United States  1188906.50
2          Canada  1182724.99
3  United Kingdom  1165387.89
4       Australia  1157750.50
5           India  1145311.33
6          France  1117231.28
7             UAE  1109749.70
8        Pakistan  1067444.22
9         Germany  1038727.08

 Insight-

This query identifies the countries that contribute the highest revenue.

 Recommendation-

Focus marketing efforts and inventory planning on high-performing countries while investigating opportunities to improve sales in lower-performing markets.

In [11]:
query = """
SELECT
    City,
    ROUND(SUM(Order_Amount),2) AS Total_Revenue
FROM orders
GROUP BY City
ORDER BY Total_Revenue DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

       City  Total_Revenue
0     Dubai     1205723.06
1    Riyadh     1200674.20
2    Mumbai     1171204.45
3     Paris     1152559.31
4   Toronto     1141321.96
5    London     1119479.98
6    Sydney     1112958.05
7    Berlin     1112034.46
8   Karachi     1107320.88
9  New York     1046767.64

Key Takeaways

The first few queries give a good overview of the business. The dataset contains a large number of orders and customers, giving enough data to analyse sales trends. Looking at total revenue and average order value also gives a useful starting point before exploring which customers, products and regions contribute the most to the business.

 Insight-

This query identifies the ten cities generating the highest revenue. These locations represent the company's strongest markets.

 Recommendation-

Increase marketing investment and inventory availability in these high-performing cities while analysing why lower-performing cities generate less revenue.

In [12]:
query = """
SELECT
    Product_Category,
    ROUND(SUM(Order_Amount),2) AS Revenue
FROM orders
GROUP BY Product_Category
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

  Product_Category     Revenue
0      Electronics  6320059.31
1   Home & Kitchen  1768963.43
2          Fashion  1323929.17
3           Sports   661447.69
4           Beauty   460243.32
5        Groceries   360727.15
6             Toys   279307.23
7            Books   195366.69

Insight-

This analysis shows which product categories contribute the most revenue.

Recommendation-

Prioritise high-performing categories for promotions and product expansion while reviewing strategies for lower-performing categories.

In [13]:
query = """
SELECT
    Customer_Segment,
    ROUND(SUM(Order_Amount),2) AS Revenue
FROM orders
GROUP BY Customer_Segment
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

  Customer_Segment     Revenue
0        Returning  4582714.19
1              New  2982575.91
2            Loyal  2659608.61
3          Premium  1145145.28

 Insight-

Different customer segments contribute differently to overall revenue.

Recommendation-

Develop targeted marketing campaigns for each customer segment to maximise sales and customer retention.

In [14]:
query = """
SELECT
    Payment_Method,
    ROUND(SUM(Order_Amount),2) AS Revenue
FROM orders
GROUP BY Payment_Method
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

     Payment_Method     Revenue
0            PayPal  1938263.16
1       Credit Card  1928578.61
2     Bank Transfer  1910678.87
3            Wallet  1889625.39
4  Cash on Delivery  1885121.18
5        Debit Card  1817776.78

 Insight-

This analysis highlights which payment methods customers prefer.

 Recommendation-

Ensure the most popular payment methods provide a seamless checkout experience while encouraging adoption of other secure payment options.

In [15]:
query = """
SELECT
    Traffic_Source,
    ROUND(SUM(Order_Amount),2) AS Revenue
FROM orders
GROUP BY Traffic_Source
ORDER BY Revenue DESC;
"""

pd.read_sql(query, conn)

   Traffic_Source     Revenue
0    Social Media  1981282.37
1          Direct  1948026.73
2           Email  1903102.31
3  Organic Search  1875668.21
4        Paid Ads  1834439.98
5        Referral  1827524.39

Insight-

This query evaluates which marketing channels generate the highest revenue.

 Recommendation-

Allocate more marketing budget towards high-performing traffic sources while optimising or reconsidering less effective channels.

Key Takeaways

 The analysis now shows where the business performs best. Some cities and product categories contribute much more revenue than others, while customer segments and payment methods reveal differences in purchasing behaviour. Looking at delivery times and return rates also highlights areas where the company could improve the customer experience.

In [16]:
query = """
SELECT
    Product_Category,
    COUNT(*) AS Total_Orders,
    SUM(CASE WHEN Returned = 'Yes' THEN 1 ELSE 0 END) AS Returned_Orders,
    ROUND(
        100.0 * SUM(CASE WHEN Returned = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS Return_Rate_Percent
FROM orders
GROUP BY Product_Category
ORDER BY Return_Rate_Percent DESC;
"""

pd.read_sql(query, conn)

  Product_Category  Total_Orders  Returned_Orders  Return_Rate_Percent
0          Fashion          6092              845                13.87
1            Books          2163              236                10.91
2           Sports          2439              239                 9.80
3      Electronics          4699              432                 9.19
4             Toys          2062              182                 8.83
5        Groceries          5380              475                 8.83
6           Beauty          2971              261                 8.78
7   Home & Kitchen          4194              363                 8.66

 Insight-

This query measures the percentage of returned orders for each product category.

Recommendation-

Investigate categories with high return rates to identify quality issues, inaccurate product descriptions or delivery-related problems.

In [17]:
query = """
SELECT
    Customer_ID,
    ROUND(SUM(Order_Amount),2) AS Total_Spent
FROM orders
GROUP BY Customer_ID
ORDER BY Total_Spent DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  Customer_ID  Total_Spent
0  CUST000459     10712.12
1  CUST006906     10179.74
2  CUST000025      9308.43
3  CUST000381      9035.20
4  CUST005303      8789.97
5  CUST000677      8682.57
6  CUST008949      8681.58
7  CUST001750      8615.22
8  CUST003335      8558.97
9  CUST005767      8272.02

 Insight-

This query identifies the company's highest-spending customers.

 Recommendation-

Reward these customers with loyalty programmes, exclusive offers and personalised promotions to improve retention.

In [18]:
query = """
SELECT
    Product_Category,
    ROUND(SUM(Profit_Amount),2) AS Total_Profit
FROM orders
GROUP BY Product_Category
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, conn)

  Product_Category  Total_Profit
0      Electronics    1040688.00
1   Home & Kitchen     379418.20
2          Fashion     344642.74
3           Sports     139758.27
4           Beauty     134401.18
5        Groceries      76057.26
6             Toys      60150.95
7            Books      40799.67

 Insight-

Revenue does not always equal profit. This analysis identifies which product categories contribute the most profit.

Recommendation-

Focus future investment and inventory on high-profit categories while reviewing pricing strategies for less profitable products.

In [19]:
query = """
SELECT
    Customer_ID,
    ROUND(SUM(Order_Amount),2) AS Total_Spent,
    RANK() OVER (
        ORDER BY SUM(Order_Amount) DESC
    ) AS Customer_Rank
FROM orders
GROUP BY Customer_ID;
"""

pd.read_sql(query, conn)

     Customer_ID  Total_Spent  Customer_Rank
0     CUST000459     10712.12              1
1     CUST006906     10179.74              2
2     CUST000025      9308.43              3
3     CUST000381      9035.20              4
4     CUST005303      8789.97              5
...          ...          ...            ...
8678  CUST005975        16.42           8679
8679  CUST004393        15.84           8680
8680  CUST008334        15.63           8681
8681  CUST005787        11.65           8682
8682  CUST005670         6.67           8683

[8683 rows x 3 columns]

Insight-

This query ranks customers based on total spending, helping identify the most valuable customers.

Recommendation-

Use customer rankings to create VIP programmes and targeted retention strategies.

In [20]:
query = """
SELECT
    Order_Date,
    ROUND(Order_Amount,2) AS Revenue,
    ROUND(
        SUM(Order_Amount) OVER(
            ORDER BY Order_Date
        ),
        2
    ) AS Running_Total
FROM orders
ORDER BY Order_Date;
"""

pd.read_sql(query, conn)

       Order_Date  Revenue  Running_Total
0      2023-01-01    68.20       10026.40
1      2023-01-01    38.73       10026.40
2      2023-01-01   153.66       10026.40
3      2023-01-01   298.37       10026.40
4      2023-01-01   105.75       10026.40
...           ...      ...            ...
29995  2026-12-31   325.17    11370043.99
29996  2026-12-31   199.07    11370043.99
29997  2026-12-31   101.95    11370043.99
29998  2026-12-31   262.05    11370043.99
29999  2026-12-31   158.76    11370043.99

[30000 rows x 3 columns]

Insight-

A running total shows cumulative revenue over time, making it easier to monitor business growth.

Recommendation-

Use cumulative revenue tracking to compare growth against sales targets and identify periods of slower performance.

In [21]:
query = """
SELECT
    strftime('%Y-%m', Order_Date) AS Month,
    ROUND(SUM(Order_Amount),2) AS Revenue
FROM orders
GROUP BY Month
ORDER BY Month;
"""

pd.read_sql(query, conn)

      Month     Revenue
0   2023-01   936076.62
1   2023-02   921195.64
2   2023-03  1010299.50
3   2023-04   924831.93
4   2023-05   913148.58
5   2023-06   918539.05
6   2023-07   930656.68
7   2023-08  1071268.49
8   2023-09   919010.17
9   2023-10   900354.21
10  2023-11   930805.06
11  2023-12   993858.06

Insight-

This query shows how revenue changes from month to month.

Recommendation-

Identify seasonal peaks and low-demand periods to improve inventory planning and marketing campaigns.

In [22]:
query = """
SELECT
    Product_Category,
    ROUND(AVG(Review_Rating),2) AS Average_Rating
FROM orders
GROUP BY Product_Category
ORDER BY Average_Rating DESC;
"""

pd.read_sql(query, conn)

  Product_Category  Average_Rating
0             Toys            4.06
1           Sports            4.06
2   Home & Kitchen            4.06
3        Groceries            4.06
4           Beauty            4.06
5      Electronics            4.05
6            Books            4.03
7          Fashion            4.01

 Insight-

Customer satisfaction varies across product categories.

Recommendation-

Investigate categories with lower ratings to improve product quality and customer experience.

 Key Takeaways-

The analysis focuses on customer value and long-term business performance. Ranking customers helps identify the most valuable buyers, while profit and monthly revenue trends give a better picture of how the business is performing over time. These insights can support decisions around marketing, inventory planning and customer retention.

 Conclusion-

This project used SQL to analyse an e-commerce sales dataset and answer a range of business questions related to customer behaviour, sales performance and profitability. By applying SQL techniques such as filtering, aggregation, grouping and window functions, it was possible to identify key trends and generate meaningful business insights.

The analysis highlighted which customers, cities and product categories contributed the most to revenue, while also examining delivery performance, return rates and monthly sales trends. These findings show how SQL can be used to transform raw data into information that supports better business decisions.

Overall, this project strengthened my understanding of SQL and demonstrated how data can be analysed to solve real business problems. In the future, this analysis could be extended by building interactive dashboards in Power BI or using machine learning models to predict customer behaviour and sales trends.